name: Jest test

on:
  pull_request:
  
jobs:
  build:
    name: Jest test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Jest test
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        run: npm run test:ci
